apiVersion: modelregistry.opendatahub.io/v1beta1
kind: ModelRegistry
metadata:
  annotations:
    openshift.io/description: 'deployment-registry Model Registry'
    openshift.io/display-name: deployment-registry
  name: deployment-registry
  namespace: rhoai-model-registries
  finalizers:
    - modelregistry.opendatahub.io/finalizer
spec:
  grpc:
    port: 9090
  mysql:
    database: metadb
    host: svc-registry-db.model-registry.svc.cluster.local
    passwordSecret:
      key: database-password
      name: model-registry-db
    port: 3306
    skipDBCreation: false
    username: root
  oauthProxy:
    port: 8443
    routePort: 443
    serviceRoute: enabled
  rest:
    port: 8080
    resources:
      limits:
        cpu: 100m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 256Mi
    serviceRoute: disabled
