apiVersion: modelregistry.opendatahub.io/v1alpha1
kind: ModelRegistry
metadata:
  annotations:
    openshift.io/description: 'deployment-registry Model Registry'
    openshift.io/display-name: deployment-registry
  name: deployment-registry
  namespace: rhoai-model-registries
  finalizers:
    - modelregistry.opendatahub.io/finalizer
spec:
  grpc:
    port: 9090
  istio:
    gateway:
      grpc:
        gatewayRoute: enabled
        port: 443
        tls:
          mode: SIMPLE
      rest:
        gatewayRoute: enabled
        port: 443
        tls:
          mode: SIMPLE
    tlsMode: ISTIO_MUTUAL
  mysql:
    database: metadb
    host: model-registry-db.model-registry.svc.cluster.local
    passwordSecret:
      key: database-password
      name: model-registry-db
    port: 3306
    skipDBCreation: false
    username: root
  rest:
    image: 'quay.io/opendatahub/model-registry:v0.2.10'
    port: 8080
    resources:
      limits:
        cpu: 100m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 256Mi
    serviceRoute: disabled
