kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  annotations:
    openshift.io/description: Can access Model Registry model-registry
    openshift.io/display-name: Registry User model-registry
  name: role-registry
  namespace: rhoai-model-registries
  labels:
    app: model-registry
    app.kubernetes.io/component: model-registry
    app.kubernetes.io/created-by: model-registry-operator
    app.kubernetes.io/instance: model-registry
    app.kubernetes.io/managed-by: model-registry
    app.kubernetes.io/name: model-registry
    app.kubernetes.io/part-of: model-registry
    component: model-registry
rules:
  - verbs:
      - get
    apiGroups:
      - ''
    resources:
      - services
    resourceNames:
      - model-registry
