kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rolebinding-model-registry
  namespace: rhoai-model-registries
  labels:
    app: model-registry
    app.kubernetes.io/component: model-registry
    app.kubernetes.io/name: model-registry
    app.kubernetes.io/part-of: model-registry
    component: model-registry
    opendatahub.io/dashboard: 'true'
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: model-registry
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: model-registry
