{{ $attendees := (.Values.attendees | int) }}
{{- range $attendee := until $attendees }}
---
kind: Namespace
apiVersion: v1
metadata:
  name: user{{ $attendee}}-mlops
  labels:
    kubernetes.io/metadata.name: user{{ $attendee}}-mlops
    opendatahub.io/dashboard: 'true'
    openshift-pipelines.tekton.dev/namespace-reconcile-version: 1.15.1
  annotations:
    openshift.io/description: 'user{{ $attendee}} MLOps Project'
    openshift.io/display-name: user{{ $attendee}}-mlops
    openshift.io/requester: user{{ $attendee}}
spec:
  finalizers:
    - kubernetes
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: admin
  namespace: user{{ $attendee }}-mlops
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: user{{ $attendee }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
{{- end }}