---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: mlops-deploy-lab-operators
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: lab-deploy-operators-appset
spec:
  goTemplate: true
  generators:
  - git:
      repoURL: "https://github.com/rhoai-mlops/deploy-lab"
      revision: main
      files:
      - path: operators/templates
  template:
    metadata:
      name: "{{ .path.basename }}"
    spec:
      destination:
        server: https://kubernetes.default.svc
        namespace: ml500
      project: mlops-deploy-lab
      sources:
        - ref: app-values
          repoURL: "https://github.com/rhoai-mlops/deploy-lab"
          targetRevision: main
        - helm:
            valueFiles:
              - $app-values/values.yaml 
          path: '{{ .chart_path }}'
          repoURL: '{{ .repo_url | default "https://github.com/rhoai-mlops/deploy-lab" }}'
          targetRevision: '{{ .target_revision | default "main" }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - Validate=true