---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-gitops-operator
  annotations:
    openshift.io/display-name: "OpenShift GitOps Operator"
  labels:
    openshift.io/cluster-monitoring: 'true'
    # meta.helm.sh/release-name: "ml500-gitops"
    # app.kubernetes.io/managed-by: "Helm"
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-gitops-operator
  namespace: openshift-gitops-operator
spec:
  channel: latest
  installPlanApproval: Automatic
  name: openshift-gitops-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  config:
    env:
      - name: ARGOCD_CLUSTER_CONFIG_NAMESPACES
        value: "openshift-gitops"
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-gitops-operator
  namespace: openshift-gitops-operator
spec: {}