{{ $attendees := (.Values.attendees | int) }}
{{- range $attendee := until $attendees }}
---
apiVersion: v1
stringData:
  password: "thisisthepassword"
  username: "user{{ $attendee }}"
kind: Secret
type: kubernetes.io/basic-auth
metadata:
  annotations:
    tekton.dev/git-0: https://gitea-gitea.apps.cluster-drfq8.drfq8.sandbox3295.opentlc.com
    sealedsecrets.bitnami.com/managed: "true"
  name: git-auth
  namespace: user{{ $attendee }}-mlops
{{- end }}